### ISSUE TITLE
Feature Request: Translate parts when deriving in part studio

### ISSUE THREAD

**Issue by TechplexEngineer** [juliaschatz/onshape-library-window#67]
Would it be possible to translate a part in the process of deriving a part in a part studio?

**Comment by juliaschatz** [comment]
Sorry for missing this- can you explain what this looks like to you? Like a menu that you can input a translation? Unfortunately there's not a way to drag it around like the Onshape insertion tool.

**Comment by TechplexEngineer** [comment]
We often use the workflow, derive, then translate by mate connector. Would be slick to have an optional mate connector selector to add the translate right in.

**Comment by juliaschatz** [comment]
The main issue with this is that to transform by mate connector, you need a
mate connector that provides the source pose. Usually when I do this I
choose a mate connector on the part itself that represents what I want to
"mate." Which isn't possible with the app because the part doesn't exist to
select until it's already been derived. Unless you do it differently?

**Comment by TechplexEngineer** [comment]
Yeah, good point. There isn't a consistent way to align parts out of the library. The two step approach is probably best. I feel like there is some context that is missing from my original post that I can't remember :(
Thanks for you consideration.
